---

- name: Create a Tenent
  hosts: POD19
  connection: local
  gather_facts: no
  collections: cisco.aci

  vars:
    tenant_name: "PROD_BRU"
    login: &login_info
      hostname: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_password}}"
      validate_certs: no
  tasks:
    - name: Create a tenant
      aci_tenant:
        <<: *login_info
        tenant: "{{ tenant_name }}"
      delegate_to: localhost

